POST https://projeto-integrador-znob.onrender.com/usuarios
Content-Type: application/json
Accept-Language: pt 

{
   
}

###

GET  https://projeto-integrador-znob.onrender.com/usuarios

###

PUT https://projeto-integrador-znob.onrender.com/usuarios/
Content-Type: application/json
Accept-Language: pt 

{
    
}

###

DELETE https://projeto-integrador-znob.onrender.com/usuarios/