POST https://projeto-integrador-znob.onrender.com/salas
Content-Type: application/json
Accept-Language: pt 

{
    "numero": 1,
    "descricao": "esta é a sala 01",
    "capacidade": 50
}

###

GET  https://projeto-integrador-znob.onrender.com/salas

###

PUT https://projeto-integrador-znob.onrender.com/salas/9081977e-a164-4744-bf8e-b226e4cad15b
Content-Type: application/json
Accept-Language: pt 

{
    "numero": 2,
    "descricao": "esta é a sala 02",
    "capacidade": 60
}

###

DELETE https://projeto-integrador-znob.onrender.com/salas/9081977e-a164-4744-bf8e-b226e4cad15b